import type { Metadata } from "next";
import { Barlow, Barlow_Condensed, Bellefair } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";

const barlow = Barlow({
  variable: "--font-barlow",
  weight: "400",
  subsets: ["latin"],
});

const barlowCondensed = Barlow_Condensed({
  variable: "--font-barlow-condensed",
  weight: "400",
  subsets: ["latin"],
});

const bellefair = Bellefair({
  variable: "--font-bellefair",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${barlow.variable} ${bellefair.variable} ${barlowCondensed.variable}`}
    >
      <body className={`antialiased text-[#fff]`}>
        <div className="relative w-screen h-screen overflow-x-hidden overflow-y-auto">
          <Header />

          {children}
        </div>
      </body>
    </html>
  );
}
